### ISSUE TITLE
Error when rendering page in Keycloak 20.0.2

### ISSUE THREAD

**Issue by MichaelJHaywood** [InseeFrLab/keycloakify#225]
When I render my login page an error is thrown by the Keycloak server. I can successfully login but I don't understand what is causing this error. 

It is complaining that an `exists` method is called with an incorrect amount of arguments. If I open the generated `login.ftl` I can see where this method is called and it is getting passed 2 arguments although it seems it should have 1.

I can't see what causes this based off of my code. 

**login.ftl code**
```
<#if messagesPerField.exists('username', 'password')>true<#else>false</#if>
```

**Keycloak Exception**
```
2023-01-12 13:18:29,836 ERROR [freemarker.runtime] (executor-thread-1) Error executing FreeMarker template part in the #attempt block: freemarker.core._TemplateModelException: Java method "org.keycloak.theme.beans.MessagesPerFieldBean.exists(String)" takes 1 argument, but 2 was given.

**Keycloak Exception**
----
FTL stack trace ("~" means nesting-related):
        - Failed at: #if messagesPerField.exists("username...  [in template "login.ftl" at line 102, column 40]
----
        at freemarker.ext.beans.SimpleMethod.unwrapArguments(SimpleMethod.java:73)
        at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:74)
        at freemarker.core.MethodCall._eval(MethodCall.java:62)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.Expression.evalToBoolean(Expression.java:177)
        at freemarker.core.Expression.evalToBoolean(Expression.java:163)
        at freemarker.core.IfBlock.accept(IfBlock.java:49)
        at freemarker.core.Environment.visit(Environment.java:347)
        at freemarker.core.Environment.visit(Environment.java:353)
        at freemarker.core.Environment.visit(Environment.java:353)
        at freemarker.core.Environment.visitAttemptRecover(Environment.java:564)
        at freemarker.core.AttemptBlock.accept(AttemptBlock.java:45)
        at freemarker.core.Environment.visit(Environment.java:383)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:347)
        at freemarker.core.Environment.visit(Environment.java:353)
        at freemarker.core.Environment.visit(Environment.java:353)
        at freemarker.core.Environment.process(Environment.java:326)
        at freemarker.template.Template.process(Template.java:383)
        at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:49)
        at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.processTemplate(FreeMarkerLoginFormsProvider.java:524)
        at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createResponse(FreeMarkerLoginFormsProvider.java:301)
        at org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider.createLoginUsernamePassword(FreeMarkerLoginFormsProvider.java:538)
        at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.challenge(UsernamePasswordForm.java:95)
        at org.keycloak.authentication.authenticators.browser.UsernamePasswordForm.authenticate(UsernamePasswordForm.java:81)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:446)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:250)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:381)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:272)
        at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1017)
        at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
        at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:338)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:194)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Login.tsx**
```
import type {FormEventHandler} from "react";
import React, {memo, useState} from "react";
import {useConstCallback} from "powerhooks/useConstCallback";
import {KcContextBase, KcProps} from "keycloakify";
import {I18n} from "../i18n/i18n";
import Template, {TemplateProps} from "keycloakify/lib/components/Template";
import {clsx} from "keycloakify/lib/tools/clsx";
import {Button, Checkbox, Col, Form, Input, Row} from "antd";

import "./Login.css"

export type LoginProps = KcProps & {
    kcContext: KcContextBase.Login;
    i18n: I18n;
    doFetchDefaultThemeResources?: boolean;
    Template?: (props: TemplateProps) => JSX.Element | null;
};

const Login = memo((props: LoginProps) => {
    const {kcContext, i18n, ...kcProps} = props;

    const {social, realm, url, usernameEditDisabled, login, auth, registrationDisabled} = kcContext;

    const {msg, msgStr} = i18n;

    const [isLoginButtonDisabled, setIsLoginButtonDisabled] = useState(false);

    const onSubmit = useConstCallback<FormEventHandler<HTMLFormElement>>(e => {
        e.preventDefault();

        setIsLoginButtonDisabled(true);

        const formElement = e.target as HTMLFormElement;

        //NOTE: Even if we login with email Keycloak expect username and password in
        //the POST request.
        formElement.querySelector("input[name='email']")?.setAttribute("name", "username");

        formElement.submit();
    });

    return (
        <Template
            {...{kcContext, i18n, ...kcProps}}
            doFetchDefaultThemeResources={false}
            displayInfo={social.displayInfo}
            displayMessage={false}
            displayWide={realm.password && social.providers !== undefined}
            headerNode={msg("doLogIn")}
            i18n={i18n}
            formNode={
                <>


                    <Row justify="center" align="middle" style={{minHeight: '100vh'}}>

                        <div id="login-container">
                            <div id="kc-form"
                                 className={clsx(realm.password && social.providers !== undefined && kcProps.kcContentWrapperClass)}>

                                <Row justify={"center"}>
                                    <div id="login-logo"/>
                                </Row>
                                <div
                                    id="kc-form-wrapper"
                                    className={clsx(
                                        realm.password && social.providers && [kcProps.kcFormSocialAccountContentClass, kcProps.kcFormSocialAccountClass]
                                    )}
                                >
                                    <div id="login-sign-in-text">
                                        {msg("loginSignInText")}
                                    </div>
                                    {realm.password && (

                                        <Form id="kc-form-login" onSubmitCapture={onSubmit} action={url.loginAction}
                                              method="post">
                                            <div id="usernameContainer" className={clsx(kcProps.kcFormGroupClass)}>
                                                {(() => {
                                                    const label = !realm.loginWithEmailAllowed
                                                        ? "username"
                                                        : realm.registrationEmailAsUsername
                                                            ? "email"
                                                            : "usernameOrEmail";

                                                    const autoCompleteHelper: typeof label = label === "usernameOrEmail" ? "username" : label;

                                                    return (

                                                            <Input
                                                                prefix={<div className="dmi-size-14 dmi-message-line"/>}
                                                                tabIndex={1}
                                                                id={autoCompleteHelper}
                                                                className={clsx(kcProps.kcInputClass)}
                                                                name={autoCompleteHelper}
                                                                defaultValue={login.username ?? ""}
                                                                type="text"
                                                                {...(usernameEditDisabled
                                                                    ? {"disabled": true}
                                                                    : {
                                                                        "autoFocus": true,
                                                                        "autoComplete": "off"
                                                                    })} />



                                                    );
                                                })()}
                                            </div>

                                            <div className={clsx(kcProps.kcFormGroupClass)}>

                                                <Form.Item
                                                    className={clsx(kcProps.kcInputClass)}
                                                    id="password-form-item"
                                                    name="password"
                                                    rules={[
                                                        {
                                                            required: true,
                                                            message: 'Please input your password!',
                                                        },
                                                    ]}
                                                >
                                                    <Input.Password id="password" name="password" tabIndex={2}
                                                                    autoComplete={"off"} prefix={<div
                                                        className="dmi-size-14 dmi-padlock-line"/>}/>
                                                </Form.Item>

                                            </div>
                                            <Row className={clsx(kcProps.kcFormGroupClass, kcProps.kcFormSettingClass)}>
                                                <Col span={12}>
                                                    <div id="kc-form-options">
                                                        {realm.rememberMe && !usernameEditDisabled && (
                                                            <div className="checkbox">
                                                                <label>
                                                                    <Row align={"middle"}>
                                                                        <Col> <Checkbox
                                                                            tabIndex={3}
                                                                            id="rememberMeCheckbox"
                                                                            name="rememberMe"
                                                                            type="checkbox"
                                                                            {...(login.rememberMe
                                                                                ? {
                                                                                    "checked": true
                                                                                }
                                                                                : {})}
                                                                        /></Col>
                                                                        <Col>
                                                                            <div
                                                                                id="rememberMeText">{msg("rememberMe")}</div>
                                                                        </Col>
                                                                    </Row>

                                                                </label>
                                                            </div>
                                                        )}
                                                    </div>
                                                </Col>
                                                <Col span={12} id="loginForgotPasswordContainer">
                                                    <div className={clsx(kcProps.kcFormOptionsWrapperClass)}>
                                                        {realm.resetPasswordAllowed && (
                                                            <span>
                                                    <a id="loginForgotPassword" tabIndex={5}
                                                       href={url.loginResetCredentialsUrl}>
                                                        {msg("doForgotPassword")}
                                                    </a>
                                                </span>
                                                        )}
                                                    </div>
                                                </Col>
                                            </Row>
                                            <div id="kc-form-buttons" className={clsx(kcProps.kcFormGroupClass)}>
                                                <input
                                                    type="hidden"
                                                    id="id-hidden-input"
                                                    name="credentialId"
                                                    {...(auth?.selectedCredential !== undefined
                                                        ? {
                                                            "value": auth.selectedCredential
                                                        }
                                                        : {})}
                                                />
                                                <Button type="primary" htmlType="submit" block
                                                        tabIndex={4}
                                                        className={clsx(
                                                            kcProps.kcButtonClass,
                                                            kcProps.kcButtonPrimaryClass,
                                                            kcProps.kcButtonBlockClass,
                                                            kcProps.kcButtonLargeClass
                                                        )}
                                                        name="login"
                                                        id="kc-login"
                                                        value={msgStr("doLogIn")}
                                                        disabled={isLoginButtonDisabled}>
                                                    {msgStr("doLogIn")}
                                                </Button>
                                            </div>
                                        </Form>
                                    )}
                                </div>
                                {realm.password && social.providers !== undefined && (
                                    <div id="kc-social-providers"
                                         className={clsx(kcProps.kcFormSocialAccountContentClass, kcProps.kcFormSocialAccountClass)}>
                                        <ul
                                            className={clsx(
                                                kcProps.kcFormSocialAccountListClass,
                                                social.providers.length > 4 && kcProps.kcFormSocialAccountDoubleListClass
                                            )}
                                        >
                                            {social.providers.map(p => (
                                                <li key={p.providerId}
                                                    className={clsx(kcProps.kcFormSocialAccountListLinkClass)}>
                                                    <a href={p.loginUrl} id={`zocial-${p.alias}`}
                                                       className={clsx("zocial", p.providerId)}>
                                                        <span>{p.displayName}</span>
                                                    </a>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                )}
                            </div>
                        </div>
                    </Row>
                </>
            }
            infoNode={
                realm.password &&
                realm.registrationAllowed &&
                !registrationDisabled && (
                    <div id="kc-registration">
                        <span>
                            {msg("noAccount")}
                            <a tabIndex={6} href={url.registrationUrl}>
                                {msg("doRegister")}
                            </a>
                        </span>
                    </div>
                )
            }
        />
    );
});

export default Login;
```

Is this an error with my code or to do with Keycloakify expecting a different version of Keycloak?

**Comment by garronej** [comment]
Hi,  
Yes I know sorry, it's a bug that have been introduced by a poorly reviewed PR.  

It has been fixed since, you just need to upgrade Keycloakify to the latest build.

**Comment by MichaelJHaywood** [comment]
Thanks for the quick response! By latest build do you mean `6.8.12`? I was using `6.8.11` before but I've tried with both and still get the error.

**Comment by MichaelJHaywood** [comment]
Thanks for the quick response! I was using `6.8.11` and tried with `6.8.12` but missed that an error was thrown during building.. I'll give it a try thank you.
